################Projeto Integrador III####################
#   Docker compose para subir ambiente php+apache+mysql #
#   imagens usadas: ambientum                           #
#########################################################

version: '3'

services:

  apache-local:
    image: ambientum/php:7.0-apache
    container_name: apache-local 
    volumes:
      - ./www/html:/var/www/app/public

    ports:
      - "8080:8080"
    links:
      - mysql-local #link do apache-php com o mysql

  mysql-local:
    image: ambientum/mysql:5.7
    container_name: mysql-local
    volumes:
      - ./mysql:/var/lib/mysql
 
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projeto_docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    user: "1000:50"  
