---
- hosts: all
  
  vars:
         ansible_python_interpreter: "/usr/bin/env python2.7"
  
  tasks:
   
   - name: Atualização de repo debian
     apt: update_cache=yes
     when: ansible_os_family == "Debian"

   - name: Atualização debian
     apt: upgrade=dist
     when: ansible_os_family == "Debian"
   
   - name: Atualização de repo redhat
     yum: name=* state=latest
     when: ansible_os_family == "RedHat"
 

